single_len_symbols = ["-", "+", "*", "/", "%", "^", "(", ")", "<", ">"]
boolean_symbols = ["&&", "||", "!"]
double_len_symbols = ["++", "--", "==", "!=", "<=", ">="]
op_equals_symbols = ["+=", "-=", "*=", "/=", "%=", "^=", "!="]
bool_equals_symbols = ["&&=", "||="]
assign_symbols = ["="]
keywords = ["print"]

disj_symbols = ["+", "-"]
conj_symbols = ["*", "/", "%"]
power_symbols = ["^"]
neg_symbols = ["-"]
incr_or_decr_symbols = ["--", "++"]
relational_symbols = ["<", ">", "<=", ">=", "==", "!="]
